version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: lms-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: lmsdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
